Set linters and .github workflow actions #11
DanSam5K/smartnote-app pull request #12
Opened 2023-05-09 10:15 UTC by DanSam5K

- Linters setup

2023-05-09 21:31 UTC, edustartech requested changes

2023-05-09 21:31 UTC, edustartech commented on .github/workflows/django.yml
> +    branches: [ master ]
should be main instead of master, as you do not have a branch called master

2023-05-09 21:31 UTC, edustartech commented on .github/workflows/django.yml
> +          python ./web/manage.py test
🫠

2023-05-12 11:21 UTC, timizuoebideri1 approved these changes

2023-05-12 11:58 UTC, merged